Better rosbag support + example
StefanFabian/ros_babel_fish pull request #7
Opened 2021-09-16 09:49 UTC by valgur

This PR makes the API a bit more flexible by:
* extracting an [`IBabelFishMessage`](https://github.com/valgur/ros_babel_fish/blob/9ad8a0bcd2ca58398741d7a5c73572d7e305e82a/ros_babel_fish/include/ros_babel_fish/babel_fish_message.h#L16-L50) interface and using it in the API methods that use `BabelFishMessage`-s in a read-only manner. This allows the creation of customized of `BabelFishMessage` variants. This is beneficial for the rosbag use case, where the messages are returned as `MessageInstance` objects that unlike `BabelFishMessage` merely reference the message type and definition info instead of storing them. Copying the message definition for each message should preferably be avoided since the definition itself is often larger than the message contents. I also made the virtual `IBabelFishMessage` methods in `BabelFishMessage` `final` to allow the compiler to de-virtualize them where possible. I think it's acceptable to have the user re-define rather than derive from `BabelFishMessage` as the class is pretty simple.
* adding two convenience overloads:
  * `MessageDescription::ConstPtr DescriptionProvider::getMessageDescription( const std::string &type, const std::string &md5, const std::string &definition );`
  * `SubMessageLocation MessageExtractor::retrieveLocationForPath( const IBabelFishMessage &msg, const std::string &path );`

I also added a simple rosbag processing example.

2021-09-24 12:18 UTC, StefanFabian commented
Thank you again for another contribution ^^
I am currently occupied with preparations for the [RoboCup German Open at the DRZ](https://rettungsrobotik.de/en/robocup-rescue-german-open-2021-drz-edition/) (German center for rescue robotics) and the [ENRICH 2021 robotics hackathon](https://enrich.european-robotics.eu/), hence, while the changes sound useful, I won't be able to have a look before mid-Octobre.
Just as a quick heads up.

2021-10-29 12:26 UTC, StefanFabian requested changes

2021-10-29 12:26 UTC, StefanFabian commented on ros_babel_fish/CMakeLists.txt
> +if (rosbag_storage_FOUND)
Are you looking for `rosbag` or `rosbag_storage`?

2021-10-29 12:26 UTC, StefanFabian commented on ros_babel_fish/examples/rosbag.cpp
> +    SubMessageLocation location = extractor.retrieveLocationForPath( msg, "header.frame_id" );
Would probably make sense to at least write a comment that you should cache the location since it doesn't make sense to recompute it for the same message type.

2021-11-02 17:46 UTC, valgur commented on ros_babel_fish/CMakeLists.txt
> +if (rosbag_storage_FOUND)
Fixed.

2021-11-02 17:50 UTC, valgur commented on ros_babel_fish/examples/rosbag.cpp
> +    SubMessageLocation location = extractor.retrieveLocationForPath( msg, "header.frame_id" );
Good point. Added that as a comment. And some more elsewhere now that I got a chance to look at the code with a fresh pair of eyes. :)

2021-11-12 12:49 UTC, merged